# Generated by Django 4.2.6 on 2023-10-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Room', 'Room')], default='Apartment', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sale_type',
            field=models.CharField(choices=[('For Rent', 'For Rent')], default='For Rent', max_length=10),
        ),
    ]
