# Generated by Django 4.2.6 on 2023-10-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_listing_home_type_alter_listing_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Room', 'Room')], default='Room', max_length=10),
        ),
    ]
